adminUser: 'miscawelo'



ipRoutes: '192.168.1.0/24,192.168.1.0/24,192.168.3.0/24,192.168.4.0/24'
publicKey: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDUTqqivn70uNTh2wT/q55kXjEjrrVpD4U6nohXjDJU8RDZ/FIMas8ZQ+T8/WAy7uXA7vfcjozvPUpJF2PsuWJ+NuV5wCL97wQJyeZS+taBvPMVnGWOecFX/1Az60fGONBngNWfZy7WrqKZHuXfBum1fgORJVCHvg36ii8IoTq5kfiJ6nsSOOgURuYCY7EtqmtY3Di8VQNgNrBz23WhmqB0ucBob5ETmPRTtj9TCtWzUg6TAQWPFMEzFlDJsCFlnzP0RTk9cPNftG+gruJ7wH6C+tqDXK5OW6AgBJ4RiNO68fG1F/qgAVL6CwrYpSPHCK3gsWDGaLGUlccOoeqA5xqpe5E+Di19BvJPcP4dJ30tGHjmZhjMoruS70Hovz1admLAqzH0n93J5cV7nXOsXMAx7Tyf0G81KpKS5z+8csdoLglFcMAbtm5aRQwHvdhVsYyhqbe1uFN8M2HYwXiZCx7bqEDrV57olVvUNqK6GZrqS9C5v42iz6c5tnWtcNW/R8qBhZkh2RIIQFcL1RDN9afTlIIM7XEVB4xoGjquW0JS1xMvk0Xp7XBk9OpnbmMiH/pRTRwU2aMevDXkmu6s/RpzEA81BRVN0YWsArPSXIGnF0cTJYfAn0fQuB5EApt5suwoiQBaV5EPFamYlgE995dKTp577eRaKkiIjDaWs0CidQ=='
debianLXCTemplate: 'local:vztmpl/debian-12-standard_12.2-1_amd64.tar.zst'
