#!/usr/bin/env sh

send_notif() {
  brightness=$(($(brightnessctl g) * 100 / 255))
  echo $brightness >> $HOME/.cache/scripts/dunst_brightness
  [ "$1" = "set" ] && exit

  dunstify "Brightness" "Device" -i $HOME/scripts/assets/icons/brightness.png -h string:x-dunst-stack-tag:brightness -h int:value:"$brightness"
}

[ "$1" = "down" ] && brightnessctl set $2%- && send_notif && exit
[ "$1" = "up" ] && brightnessctl set +$2% && send_notif && exit
[ "$1" = "set" ] && brightnessctl set $2% && send_notif "$1" && exit
