#!/usr/bin/env sh

kb_device="asus::kbd_backlight"

send_notif() {
  kb_backlight=$(brightnessctl --device=$kb_device g)
  echo $kb_backlight >> $HOME/.cache/scripts/dunst_kb_backlight
  [ "$1" = "set" ] && exit

  dunstify "Brightness" "Keyboard" -i $HOME/scripts/assets/icons/keyboard.png -h string:x-dunst-stack-tag:kb_brightness -h int:value:"$(($kb_backlight * 33))"
}

[ "$1" = "down" ] && if [[ $(brightnessctl --device=$kb_device g) > 0 ]]; then asusctl -p ; fi && send_notif && exit
[ "$1" = "up" ] && if [[ $(brightnessctl --device=$kb_device g) < 3 ]]; then asusctl -n ; fi && send_notif && exit
[ "$1" = "set" ] && brightnessctl --device=$kb_device set $2 && send_notif "$1" && exit
