#!/bin/sh

function handle {
    if [[ ${1:0:12} == "monitoradded" ]]; then
        hyprctl keyword monitor desc:Thermotrex Corporation TL140ADXP01, disable
    elif [[ ${1:0:14} == "monitorremoved" ]]; then
        hyprctl keyword monitor desc:Thermotrex Corporation TL140ADXP01, 2560x1600@60, 0x0, 1, bitdepth, 10
    fi
}

socat - "UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock" | while read -r line; do handle "$line"; done
