#!/usr/bin/env sh

# Eww
killall eww ; eww --force-wayland daemon &
eww open topBar &
eww open bottomBar &

# Eww listen
echo $(($(brightnessctl g) * 100 / 255)) > $HOME/.cache/dunst_brightness
echo $(($(brightnessctl --device='asus::kbd_backlight' g) * 100 / 255)) > $HOME/.cache/dunst_kb_brightness
echo $(pamixer --get-volume) > $HOME/.cache/scripts/dunst_volume
asusctl bios -O true ; echo $(asusctl bios -o | cut -d ' ' -f 4) > $HOME/.cache/scripts/eww_screen
rfkill | grep -qE "wlan.* blocked" && echo disabled > $HOME/.cache/scripts/eww_wlan_status || echo enabled > $HOME/.cache/scripts/eww_wlan_status
rfkill | grep -qE "bluetooth.* blocked" && echo disabled > $HOME/.cache/scripts/eww_bluetooth_status || echo enabled > $HOME/.cache/scripts/eww_bluetooth_status

# Hyprland plugin manager
hyprpm reload

# Polkit
/usr/lib/polkit-kde-authentication-agent-1 &

# Autostart
killall dunst ; dunst &
killall rog-control-center ; rog-control-center &

# Background
killall swaybg ; swaybg -i $HOME/Pictures/Wallpapers/$(ls $HOME/Pictures/Wallpapers | sort -R | tail -1) &

# Swayilde
killall swayidle ; swayidle -w \
    timeout 300 'brightnessctl -s ; [[ $(pactl list | grep RUNNING) ]] || [[ $(brightnessctl set 0) ]]' \
    resume 'brightnessctl -r' \
    timeout 600 '[[ $(pactl list | grep RUNNING) ]] || [[ $(hyprctl dispatch dpms off) ]]' \
    resume 'hyprctl dispatch dpms on' \
    timeout 900 '[[ $(pactl list | grep RUNNING) ]] || [[ $(systemctl suspend-then-hibernate) ]]' \
    before-sleep 'swaylock -C $HOME/.config/swaylock/config' &

# Clipboard
killall wl-paste ; cliphist wipe
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# XDG Desktop Portal
sleep 1
killall -e xdg-desktop-portal-hyprland
killall -e xdg-desktop-portal-wlr
killall xdg-desktop-portal
/usr/lib/xdg-desktop-portal-hyprland &
sleep 2
/usr/lib/xdg-desktop-portal &

# Secure Boot
if [[ ! $(sbctl status | grep -E "Secure.*Enabled") ]]; then
    dunstify --urgency critical "Secure boot is disabled" "Reboot now and enable secure boot!"
fi

dunstify "Finished Hyprland startup" "Welcome $(whoami)!" -i $HOME/scripts/assets/icons/hyprland.png -h string:x-dunst-stack-tag:welcome_message
