- name: Create 'PiHole' container
  proxmox:
    vmid: 100
    node: pve0
    api_user: root@pam
    api_password: '{{ pveRootPass }}'
    api_host: pve0
    hostname: pihole
    storage: local-lvm
    password: '{{ pveRootPass }}'
    cores: 2
    memory: 512
    swap: 512
    disk: local-lvm:vm-100-disk-0,size=4G
    netif: '{"net0":"name=eth0,ip=192.168.1.100/24,gw=192.168.1.1,bridge=vmbr0"}'
    onboot: true
    pubkey: '{{ publicKey }}'
    # ostemplate: '{{ lxcTemplateDebian }}'
    update: true
    features:
      - nesting=1
    state: present

- name: Create 'Caddy' container
  proxmox:
    vmid: 101
    node: pve0
    api_user: root@pam
    api_password: '{{ pveRootPass }}'
    api_host: pve0
    hostname: caddy
    storage: local-lvm
    password: '{{ pveRootPass }}'
    cores: 1
    memory: 512
    swap: 512
    disk: local-lvm:vm-101-disk-0,size=2G
    netif: '{"net0":"name=eth0,ip=192.168.1.101/24,gw=192.168.1.1,bridge=vmbr0"}'
    onboot: true
    pubkey: '{{ publicKey }}'
    # ostemplate: '{{ lxcTemplateDebian }}'
    update: true
    features:
      - nesting=1
    state: present

- name: Start all containers
  proxmox:
    vmid: '{{ item }}'
    api_user: root@pam
    api_password: '{{ pveRootPass }}'
    api_host: pve0
    state: started
  with_items:
    - 100
    - 101
