#!/usr/bin/env sh

# [[ $(id -u) -eq 0 ]] || { echo >&2 "Must be root to run script"; exit 1; }

distro="Arch Linux"
espDir="/boot"
drive="nvme0n1"
driveMainPartition="p3"
swapfile="/swap/swapfile"

create_ukis () {
    rootUUID=$(blkid | grep $drive$driveMainPartition | cut -d '"' -f 2)
    luksOptions=""
    swap_uuid=$(blkid | grep cryptroot | cut -d '"' -f 4)
    swap_offset=$(btrfs inspect-internal map-swapfile -r $swapfile)
    hibernation="resume=UUID="$swap_uuid" resume-offset="$swap_offset
    kernelParams="nowatchdog loglevel=3 rootflags=subvol=@ zswap.enabled=0 amdgpu.ppfeaturemask=0xffffffff"

    echo "root=UUID=$rootUUID $luksOptions $hibernation $kernelParams" > /etc/kernel/cmdline

    for vmlinuz in $espDir/vmlinuz* ; do
        kernel=${vmlinuz#*-}

        cat $espDir/amd-ucode.img $espDir/booster-$kernel.img > /tmp/$kernel.img
        stubLine=$(objdump -h "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" | tail -2 | head -1)
        stubSize=0x$(echo "$stubLine" | awk '{print $3}')
        stubOffs=0x$(echo "$stubLine" | awk '{print $4}')
        osrelOffs=$((stubSize + stubOffs))
        cmdlineOffs=$((osrelOffs + $(stat -c%s "/usr/lib/os-release")))
        linuxOffs=$((cmdlineOffs + $(stat -c%s "/etc/kernel/cmdline")))
        initrdOffs=$((linuxOffs + $(stat -c%s "$vmlinuz")))

        objcopy \
            --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=$(printf 0x%x $osrelOffs) \
            --add-section .cmdline="/etc/kernel/cmdline" --change-section-vma .cmdline=$(printf 0x%x $cmdlineOffs) \
            --add-section .linux="$vmlinuz" --change-section-vma .linux=$(printf 0x%x $linuxOffs) \
            --add-section .initrd="/tmp/$kernel.img" --change-section-vma .initrd=$(printf 0x%x $initrdOffs) \
            "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "$espDir/EFI/Linux/$kernel.efi"

        sbctl sign -s $espDir/EFI/Linux/$kernel.efi &> /dev/null
    done
}

boot_order () {
    efibootmgr

    read -p "Boot order: " bootOrder
    efibootmgr -o $bootOrder
    while [ $? -ne 0 ]; do
        read -p "Boot order: " bootOrder
        efibootmgr -o $bootOrder
    done
}

update_efistub () {
    for vmlinuz in /boot/vmlinuz* ; do
        kernel=${vmlinuz#*-}
        label="$distro ($kernel)"

        efibootmgr -q -BL "$label"

        efibootmgr -q -c -d /dev/$drive -L "$label" -l EFI/Linux/$kernel.efi
    done

    efibootmgr
}

getopts 'ceosh' action
case "$action" in
    c)
        create_ukis
        exit 0
        ;;
    e)
        update_efistub
        exit 0
        ;;
    o)
        boot_order
        exit 0
        ;;
    s)
        sbctl list-files
        efibootmgr

        read -p "Boot order: " bootOrder
        efibootmgr -o $bootOrder
        while [ $? -ne 0 ]; do
            read -p "Boot order: " bootOrder
            efibootmgr -o $bootOrder
        done
        exit 0
        ;;
    h)
        echo -e "Usage: $(basename $0) <action>\n\nActions:\n  -c  Create Unified Kernel Images\n  -e  Update EFISTUB entries\n  -o  Modify boot order\n  -s  Check status and update boot order"
        exit 0
        ;;

    ?)
        echo "Usage: $(basename $0) <action>, use -h to see all actions."
        exit 1
        ;;
esac
