#!/usr/bin/bash

# Variables
efi_dir="/boot"
ucode=amd-ucode.img
luks_options="discard"
swapfile="/swapfile"
kernel_params="nowatchdog quiet zswap.enabled=0 amdgpu.ppfeaturemask=0xffffffff"

# Distro name
distro=$(grep PRETTY_NAME /etc/os-release | cut -d '"' -f 2)

# Root partition
root_uuid=$(sudo blkid | grep LUKS | cut -d '"' -f 2)

# Boot partition
boot_partition="$(lsblk -l | grep boot | cut -d ' ' -f 1)"
boot_drive="/dev/"${boot_partition%p*}
boot_part=${boot_partition#*p}

# Swap and hibernation
swap_uuid=$(grep root -A1 /etc/fstab | tail -n 1 |  sed -e 's/.*UUID=//' | cut -d $'\t' -f 1)
swap_offset=$(sudo filefrag -v /swapfile | awk '$1=="0:" {print substr($4, 1, length($4)-2)}')
hibernation="resume=UUID="$swap_uuid" resume-offset="$swap_offset

# LUKS options
luks_options="rd.luks.options="$luks_options

rm /tmp/cmdline &> /dev/null
echo "root=UUID="$root_uuid" rw "$luks_options" "$hibernation" "$kernel_params > /tmp/cmdline

for vmlinuz in $efi_dir/vmlinuz*
do

    kernel=${vmlinuz#*-}

    cat $efi_dir/$ucode $efi_dir/booster-$kernel.img > /tmp/$kernel.img
    stub_line=$(objdump -h "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" | tail -2 | head -1)
    stub_size=0x$(echo "$stub_line" | awk '{print $3}')
    stub_offs=0x$(echo "$stub_line" | awk '{print $4}')
    osrel_offs=$((stub_size + stub_offs))
    cmdline_offs=$((osrel_offs + $(stat -c%s "/usr/lib/os-release")))
    linux_offs=$((cmdline_offs + $(stat -c%s "/tmp/cmdline")))
    initrd_offs=$((linux_offs + $(stat -c%s "$vmlinuz")))

    objcopy \
        --add-section .osrel="/usr/lib/os-release" --change-section-vma .osrel=$(printf 0x%x $osrel_offs) \
        --add-section .cmdline="/tmp/cmdline" --change-section-vma .cmdline=$(printf 0x%x $cmdline_offs) \
        --add-section .linux="$vmlinuz" --change-section-vma .linux=$(printf 0x%x $linux_offs) \
        --add-section .initrd="/tmp/$kernel.img" --change-section-vma .initrd=$(printf 0x%x $initrd_offs) \
        "/usr/lib/systemd/boot/efi/linuxx64.efi.stub" "$kernel.efi"

    sudo mv $efi_dir/EFI/Linux/$kernel.efi $efi_dir/EFI/Linux/$kernel-fallback.efi
    sudo cp $kernel.efi $efi_dir/EFI/Linux/$kernel.efi
    sudo rm $kernel.efi

    entry=$(efibootmgr | grep "($kernel)" | grep -oP "(?<=Boot).*(?=\*)")
    if [[ ! -z $entry ]]; then
        for i in $(echo $entry); do
            sudo efibootmgr -Bb "$i" &> /dev/null
        done
    fi

    sudo efibootmgr --create --disk $boot_drive --part $boot_part --label "$distro ($kernel)" --loader 'EFI\Linux\'$kernel.efi &> /dev/null

done

sudo sbctl sign-all

efibootmgr
