#!/usr/bin/env sh

eco_mode() {
    sudo ryzenadj -a 10000 -b 5000 -c 5000 --power-saving
}

limit_temp() {
    sudo ryzenadj -f $1
}

[ "$1" = "eco" ] && eco_mode && exit
[ "$1" = "temp" ] && limit_temp "$2" && exit
