---

- hosts: proxmox
  become: true
  gather_facts: false
  vars_files:
    - roles/common/vars/main.yml
    - roles/proxmox/vars/main.yml
  tasks:

  - name: Install Tailscale repository and GPG keys
    uri:
      url: '{{ item.url }}'
      method: GET
      follow_redirects: safe
      dest: '{{ item.dest }}'
      creates: '{{ item.dest }}'
    with_items:
      - { url: 'https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg', dest: '/usr/share/keyrings/tailscale-archive-keyring.gpg' }
      - { url: 'https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list', dest: '/etc/apt/sources.list.d/tailscale.list' }

  - name: Install base packages
    apt:
      update_cache: yes
      name:
      - sudo
      - neovim
      - tailscale
      - python3-proxmoxer

  - name: Create containers from list
    proxmox:
      vmid: '{{ item.vmid }}'
      node: pve0
      api_user: root@pam
      api_password: '{{ pveRootPass }}'
      api_host: pve0
      hostname: '{{ item.hostname }}'
      storage: local-lvm
      password: '{{ pveRootPass }}'
      cores: '{{ item.cores }}'
      memory: '{{ item.memory }}'
      swap: '{{ item.swap }}'
      disk: 'local-lvm:{{ item.diskSize }}'
      netif: '{"net0":"name=eth0,ip=192.168.1.{{ item.vmid | int }}/24,gw=192.168.1.1,bridge=vmbr0"}'
      onboot: true
      pubkey: '{{ publicKey }}'
      ostemplate: '{{ lxcTemplateDebian }}'
      # update: true
      features:
        - nesting=1
      state: present
    with_items: '{{ lxcHosts }}'

  - name: Start all containers
    proxmox:
      vmid: '{{ item.vmid }}'
      api_user: root@pam
      api_password: '{{ pveRootPass }}'
      api_host: pve0
      state: started
    with_items: '{{ lxcHosts }}'

  - name: Add Tailscale support for all containers
    block:
      - name: Allow cGroup2 devices
        lineinfile:
          path: '/etc/pve/lxc/{{ item.vmid }}.conf'
          regexp: '^lxc.cgroup2.devices.allow:'
          line: 'lxc.cgroup2.devices.allow: c 10:200 rwm'
        with_items: '{{ lxcHosts }}'
        register: lxcFile

      - name: Bind 'tun' device
        lineinfile:
          path: '/etc/pve/lxc/{{ item.vmid }}.conf'
          regexp: '^lxc.mount.entry:'
          line: 'lxc.mount.entry: /dev/net/tun dev/net/tun none bind,create=file'
        with_items: '{{ lxcHosts }}'
        register: lxcFile

  - name: Reboot all containers
    proxmox:
      vmid: '{{ item.vmid }}'
      api_user: root@pam
      api_password: '{{ pveRootPass }}'
      api_host: pve0
      state: restarted
    with_items: '{{ lxcHosts }}'
    when: lxcFile.changed
    register: lxcRestarted

- hosts: containers
  user: root
  vars_files:
    - roles/common/vars/main.yml
  tasks:

  - name: Install Tailscale repository and GPG keys
    uri:
      url: '{{ item.url }}'
      method: GET
      follow_redirects: safe
      dest: '{{ item.dest }}'
      creates: '{{ item.dest }}'
    with_items:
      - { url: 'https://pkgs.tailscale.com/stable/debian/bookworm.noarmor.gpg', dest: '/usr/share/keyrings/tailscale-archive-keyring.gpg' }
      - { url: 'https://pkgs.tailscale.com/stable/debian/bookworm.tailscale-keyring.list', dest: '/etc/apt/sources.list.d/tailscale.list' }
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Install base packages
    apt:
      update_cache: yes
      name:
      - neovim
      - tailscale
    when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'

  - name: Tailscale up
    command:
      argv:
        - /usr/bin/tailscale
        - up
        - '--auth-key={{ tsAuthKey }}'

- hosts: pihole
  user: root
  vars_files:
    - roles/common/vars/main.yml
  tasks:
    - import_role:
        name: roles/pihole
        tasks_from: bootstrap.yml

- hosts: caddy
  user: root
  vars_files:
    - roles/common/vars/main.yml
  tasks:
    - import_role:
        name: roles/caddy
        tasks_from: bootstrap.yml
