proxmox:
  hosts:
    pve0:
      ansible_host: 10.92.27.200
    # pbs0:
    #   ansible_host: 10.92.27.201
  vars:
    ansible_port: 6304

# nas:
#   hosts:
#     truenas:
#       ansible_host: 10.92.27.201
#   vars:
#     ansible_port: 6304

workstations:
  hosts:
    miscawelo-arch:
      ansible_host: 10.92.27.230
  vars:
    ansible_port: 6304


containers:
  hosts:
    pihole:
      ansible_host: 10.92.27.100
    caddy:
      ansible_host: 10.92.27.101
    jackett:
      ansible_host: 10.92.27.102
    radarr:
      ansible_host: 10.92.27.103
    sonarr:
      ansible_host: 10.92.27.104
    qbittorrent:
      ansible_host: 10.92.27.105
        # lxc.idmap: u 0 100000 1005
        # lxc.idmap: g 0 100000 1005
        # lxc.idmap: u 1005 1005 1
        # lxc.idmap: g 1005 1005 1
        # lxc.idmap: u 1006 101006 64530
        # lxc.idmap: g 1006 101006 64530
    plex:
      ansible_host: 10.92.27.106
        # lxc.cgroup2.devices.allow: a
        # lxc.cap.drop:
        # lxc.cgroup2.devices.allow: c 188:* rwm
        # lxc.cgroup2.devices.allow: c 189:* rwm
        # lxc.mount.entry: /dev/serial/by-id  dev/serial/by-id  none bind,optional,create=dir
        # lxc.mount.entry: /dev/ttyUSB0       dev/ttyUSB0       none bind,optional,create=file
        # lxc.mount.entry: /dev/ttyUSB1       dev/ttyUSB1       none bind,optional,create=file
        # lxc.mount.entry: /dev/ttyACM0       dev/ttyACM0       none bind,optional,create=file
        # lxc.mount.entry: /dev/ttyACM1       dev/ttyACM1       none bind,optional,create=file
        # lxc.cgroup2.devices.allow: c 226:0 rwm
        # lxc.cgroup2.devices.allow: c 226:128 rwm
        # lxc.cgroup2.devices.allow: c 29:0 rwm
        # lxc.mount.entry: /dev/fb0 dev/fb0 none bind,optional,create=file
        # lxc.mount.entry: /dev/dri dev/dri none bind,optional,create=dir
        # lxc.mount.entry: /dev/dri/renderD128 dev/dri/renderD128 none bind,optional,create=file
    nextcloud:
      ansible_host: 10.92.27.107
    paperless:
      ansible_host: 10.92.27.108
    immich:
      ansible_host: 10.92.27.109
    homepage:
      ansible_host: 10.92.27.110
    vorta:
      ansible_host: 10.92.27.111

  # ntfy:
# ansible_host: 10.92.27.
# cores: 1
# features: keyctl=1,nesting=1
# memory: 512
# ostype: debian
# rootfs: local-lvm:vm-102-disk-1,size=2G
# swap: 512

  # ombi:
# ansible_host: 10.92.27.
# cores: 2
# features: keyctl=1,nesting=1
# memory: 2048
# ostype: debian
# rootfs: local-lvm:vm-102-disk-1,size=4G
# swap: 512
  # overseer:
# ansible_host: 10.92.27.
# cores: 2
# features: keyctl=1,nesting=1
# memory: 2048
# ostype: debian
# rootfs: local-lvm:vm-102-disk-1,size=4G
# swap: 512
  # guacamole:
# ansible_host: 10.92.27.
# cores: 2
# features: keyctl=1,nesting=1
# memory: 2048
# ostype: debian
# rootfs: local-lvm:vm-102-disk-1,size=4G
# swap: 512
